
package systemlogic.processcentricservices.soap.sw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Health", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Health {


    /**
     * 
     * @param personId
     * @return
     *     returns systemlogic.processcentricservices.soap.sw.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.ReadPersonResponse")
    @Action(input = "http://sw.soap.processcentricservices.systemlogic/Health/readPersonRequest", output = "http://sw.soap.processcentricservices.systemlogic/Health/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId);

    /**
     * 
     * @return
     *     returns systemlogic.processcentricservices.soap.sw.ReadPersonListResponse.People
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.ReadPersonListResponse")
    @Action(input = "http://sw.soap.processcentricservices.systemlogic/Health/readPersonListRequest", output = "http://sw.soap.processcentricservices.systemlogic/Health/readPersonListResponse")
    public systemlogic.processcentricservices.soap.sw.ReadPersonListResponse.People readPersonList();

    /**
     * 
     * @param person
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.CreatePersonResponse")
    @Action(input = "http://sw.soap.processcentricservices.systemlogic/Health/createPersonRequest", output = "http://sw.soap.processcentricservices.systemlogic/Health/createPersonResponse")
    public Long createPerson(
        @WebParam(name = "person", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.UpdatePersonResponse")
    @Action(input = "http://sw.soap.processcentricservices.systemlogic/Health/updatePersonRequest", output = "http://sw.soap.processcentricservices.systemlogic/Health/updatePersonResponse")
    public Long updatePerson(
        @WebParam(name = "person", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/")
        Person person);

    /**
     * 
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.DeletePersonResponse")
    @Action(input = "http://sw.soap.processcentricservices.systemlogic/Health/deletePersonRequest", output = "http://sw.soap.processcentricservices.systemlogic/Health/deletePersonResponse")
    public int deletePerson(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId);

    /**
     * 
     * @param personId
     * @param type
     * @return
     *     returns systemlogic.processcentricservices.soap.sw.ReadPersonHistoryResponse.MeasureProfile
     */
    @WebMethod
    @WebResult(name = "MeasureProfile", targetNamespace = "")
    @RequestWrapper(localName = "readPersonHistory", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.ReadPersonHistory")
    @ResponseWrapper(localName = "readPersonHistoryResponse", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.ReadPersonHistoryResponse")
    @Action(input = "http://sw.soap.processcentricservices.systemlogic/Health/readPersonHistoryRequest", output = "http://sw.soap.processcentricservices.systemlogic/Health/readPersonHistoryResponse")
    public systemlogic.processcentricservices.soap.sw.ReadPersonHistoryResponse.MeasureProfile readPersonHistory(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @return
     *     returns systemlogic.processcentricservices.soap.sw.ReadMeasureTypesResponse.MeasureProfile
     */
    @WebMethod
    @WebResult(name = "MeasureProfile", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureTypes", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.ReadMeasureTypes")
    @ResponseWrapper(localName = "readMeasureTypesResponse", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.ReadMeasureTypesResponse")
    @Action(input = "http://sw.soap.processcentricservices.systemlogic/Health/readMeasureTypesRequest", output = "http://sw.soap.processcentricservices.systemlogic/Health/readMeasureTypesResponse")
    public systemlogic.processcentricservices.soap.sw.ReadMeasureTypesResponse.MeasureProfile readMeasureTypes();

    /**
     * 
     * @param mid
     * @param personId
     * @param type
     * @return
     *     returns systemlogic.processcentricservices.soap.sw.ReadPersonMeasureResponse.MeasureProfile
     */
    @WebMethod
    @WebResult(name = "MeasureProfile", targetNamespace = "")
    @RequestWrapper(localName = "readPersonMeasure", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.ReadPersonMeasure")
    @ResponseWrapper(localName = "readPersonMeasureResponse", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.ReadPersonMeasureResponse")
    @Action(input = "http://sw.soap.processcentricservices.systemlogic/Health/readPersonMeasureRequest", output = "http://sw.soap.processcentricservices.systemlogic/Health/readPersonMeasureResponse")
    public systemlogic.processcentricservices.soap.sw.ReadPersonMeasureResponse.MeasureProfile readPersonMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "mid", targetNamespace = "")
        Long mid);

    /**
     * 
     * @param measure
     * @param data
     * @param personId
     * @param value
     * @return
     *     returns systemlogic.processcentricservices.soap.sw.SavePersonMeasureResponse.MeasureHistory
     */
    @WebMethod
    @WebResult(name = "measureHistory", targetNamespace = "")
    @RequestWrapper(localName = "savePersonMeasure", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.SavePersonMeasure")
    @ResponseWrapper(localName = "savePersonMeasureResponse", targetNamespace = "http://sw.soap.processcentricservices.systemlogic/", className = "systemlogic.processcentricservices.soap.sw.SavePersonMeasureResponse")
    @Action(input = "http://sw.soap.processcentricservices.systemlogic/Health/savePersonMeasureRequest", output = "http://sw.soap.processcentricservices.systemlogic/Health/savePersonMeasureResponse")
    public systemlogic.processcentricservices.soap.sw.SavePersonMeasureResponse.MeasureHistory savePersonMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measure", targetNamespace = "")
        String measure,
        @WebParam(name = "value", targetNamespace = "")
        Float value,
        @WebParam(name = "data", targetNamespace = "")
        String data);

}
